Repository BCA-CTF/problems, pull requests merged in 2019-01, with the labels that each got.

#18 Rename basic password problems, move to binary folder
  binary/basic-password-1/compiled.exe
  binary/basic-password-1/password.c
  binary/basic-password-1/problem.md
  binary/basic-password-1/solution.py
  binary/basic-password-2/compiled.exe
  binary/basic-password-2/password.c
  binary/basic-password-2/problem.md
Labels: classification

#21 Tweak Styleguide, fix first problem.
  STYLEGUIDE.md
  miscellaneous/hello-world/README.md
  miscellaneous/hello-world/solution/README.md
Labels: problem, structure

#22 Update executable policies
  .gitignore
  CONTRIBUTING.md
  STYLEGUIDE.md
Labels: structure

#26 [REVERSING] Guess the Flag - Scratch
  programming/guess-the-flag/README.md
  programming/guess-the-flag/solution/README.md
  programming/guess-the-flag/source-code/README.md
  programming/guess-the-flag/source-code/project.sb3
  reversing/guess-the-flag/README.md
  reversing/guess-the-flag/solution/README.md
  reversing/guess-the-flag/source-code/README.md
  reversing/guess-the-flag/source-code/project.sb3
Labels: problem

#19 [WEB] Cookie Clicker problem
  web/cookie-clicker/README.md
  web/cookie-clicker/solution/README.md
  web/cookie-clicker/source-code/README.md
  web/cookie-clicker/source-code/config.json
  web/cookie-clicker/source-code/index.js
  web/cookie-clicker/source-code/package-lock.json
  web/cookie-clicker/source-code/package.json
  web/cookie-clicker/source-code/static/cookie-clicker.css
  web/cookie-clicker/source-code/static/cookie-clicker.js
  web/cookie-clicker/source-code/static/index.html
  web/cookie-clicker/source-code/static/notenoughcookies.html
  web/cookie-clicker/source-code/templates/shop.hbs
Labels: problem

#28 Add .idea folder to .gitignore
  .gitignore
Labels: structure

#32 Delete duplicate `guess-the-flag` directory
  programming/guess-the-flag/README.md
  programming/guess-the-flag/solution/README.md
  programming/guess-the-flag/source-code/README.md
  programming/guess-the-flag/source-code/project.sb3
Labels: structure

#27 [WEB] White-Out
  web/white-out/README.md
  web/white-out/solution/README.md
Labels: problem

#33 [Cryptography] A Major Problem
  cryptography/a-major-problem/README.md
  cryptography/a-major-problem/solution/README.md
Labels: problem

#36 Create README.md
  cryptography/winningdigits/README.md
Labels: problem

#34 Fix styleguide, make problems conform.
  STYLEGUIDE.md
  binary/basic-password-1/solution/README.md
  binary/basic-password-2/solution/README.md
  cryptography/a-major-problem/README.md
  cryptography/a-major-problem/solution/README.md
  miscellaneous/hello-world/README.md
  miscellaneous/hello-world/solution/README.md
  reversing/bitwise/solution/README.md
  reversing/guess-the-flag/README.md
  reversing/guess-the-flag/solution/README.md
  web/client side/solution/README.md
  web/cookie-clicker/README.md
  web/cookie-clicker/solution/README.md
  web/inspect/README.md
  web/inspect/solution/README.md
  web/user-agent/solution/README.md
  web/white-out/README.md
  web/white-out/solution/README.md
Labels: enhancement, structure

#42 Solution patch
  binary/basic-password-1/solution/README.md
  binary/basic-password-2/solution/README.md
Labels: enhancement, problem

#39 [Reversing] Compression
  reversing/compression/README.md
  reversing/compression/required-files/999
  reversing/compression/solution/README.md
Labels: problem

#40 [FORENSICS] The Study of Roofs
  forensics/study-of-roofs/README.md
  forensics/study-of-roofs/required-files/dem_shingles.jpg
  forensics/study-of-roofs/solution/README.md
  forensics/study-of-roofs/source-code/dem_shingles.jpg
  forensics/study-of-roofs/source-code/extr4_fil3.jpg
Labels: problem

#43 [FORENSICS] Two problems
  forensics/split-the-red/README.md
  forensics/split-the-red/required-files/redsea.png
  forensics/split-the-red/solution/README.md
  forensics/split-the-red/source-code/file
  forensics/split-the-red/source-code/redsea.psd
  forensics/wavey/README.md
  forensics/wavey/required-files/straightfire.wav
  forensics/wavey/solution/README.md
  forensics/wavey/source-code/file
  forensics/wavey/source-code/flag.bmp
  forensics/wavey/source-code/flag.jpg
  forensics/wavey/source-code/flag.png
  forensics/wavey/source-code/straightfire.wav
Labels: problem

#44 Create Problem File Headers
  cryptography/file-headers/README.md
  cryptography/file-headers/required-files/flag.png
  cryptography/file-headers/solution/README.md
Labels: problem
